### ISSUE TITLE
Routes for Javascript and CSS

### ISSUE THREAD

**Issue by alexandre-mbm** [alexandre-mbm/toggl-chart#3]
```console
$ rails server
=> Booting Puma
=> Rails 5.0.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.7.1 (ruby 2.4.0-p0), codename: Snowy Sagebrush
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
Started GET "/" for ::1 at 2017-03-03 15:19:01 -0300
Processing by WelcomeController#index as HTML
  Rendering welcome/index.html.erb within layouts/application
  Rendered welcome/index.html.erb within layouts/application (2.3ms)
Completed 200 OK in 295ms (Views: 273.3ms)


Started GET "/stylesheets/application.css" for ::1 at 2017-03-03 15:19:02 -0300
  
ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):
  
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
vendor/bundle/ruby/2.4.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:135:in `call_app'
vendor/bundle/ruby/2.4.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:28:in `block in call'
vendor/bundle/ruby/2.4.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:18:in `catch'
vendor/bundle/ruby/2.4.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:18:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/quiet_assets.rb:13:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/request_id.rb:24:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/static.rb:136:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/engine.rb:522:in `call'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/configuration.rb:232:in `call'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/server.rb:578:in `handle_request'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/server.rb:415:in `process_client'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/server.rb:275:in `block in run'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
Started GET "/javascripts/application.js" for ::1 at 2017-03-03 15:19:02 -0300
  
ActionController::RoutingError (No route matches [GET] "/javascripts/application.js"):
  
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
vendor/bundle/ruby/2.4.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:135:in `call_app'
vendor/bundle/ruby/2.4.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:28:in `block in call'
vendor/bundle/ruby/2.4.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:18:in `catch'
vendor/bundle/ruby/2.4.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:18:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/quiet_assets.rb:13:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/request_id.rb:24:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/static.rb:136:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/engine.rb:522:in `call'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/configuration.rb:232:in `call'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/server.rb:578:in `handle_request'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/server.rb:415:in `process_client'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/server.rb:275:in `block in run'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
  Rendering vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout
  Rendering vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.4ms)
  Rendered collection of vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/routes/_route.html.erb [2 times] (4.2ms)
  Rendering vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout
  Rendered vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/routes/_table.html.erb (13.0ms)
  Rendering vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.0ms)
  Rendered collection of vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/routes/_route.html.erb [2 times] (2.4ms)
  Rendering vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/routes/_table.html.erb (2.0ms)
  Rendered vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.8ms)
  Rendered vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (139.8ms)
  Rendering vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (2.0ms)
  Rendered vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (117.4ms)
Started GET "/" for ::1 at 2017-03-03 15:19:30 -0300
Processing by WelcomeController#index as HTML
  Rendering welcome/index.html.erb within layouts/application
  Rendered welcome/index.html.erb within layouts/application (1.6ms)
Completed 200 OK in 16ms (Views: 14.6ms)


Started GET "/stylesheets/application.css" for ::1 at 2017-03-03 15:19:31 -0300
  
ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):
  
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
vendor/bundle/ruby/2.4.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:135:in `call_app'
vendor/bundle/ruby/2.4.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:28:in `block in call'
vendor/bundle/ruby/2.4.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:18:in `catch'
vendor/bundle/ruby/2.4.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:18:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/quiet_assets.rb:13:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/request_id.rb:24:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/static.rb:136:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/engine.rb:522:in `call'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/configuration.rb:232:in `call'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/server.rb:578:in `handle_request'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/server.rb:415:in `process_client'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/server.rb:275:in `block in run'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
Started GET "/javascripts/application.js" for ::1 at 2017-03-03 15:19:31 -0300
  
ActionController::RoutingError (No route matches [GET] "/javascripts/application.js"):
  
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
vendor/bundle/ruby/2.4.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:135:in `call_app'
vendor/bundle/ruby/2.4.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:28:in `block in call'
vendor/bundle/ruby/2.4.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:18:in `catch'
vendor/bundle/ruby/2.4.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:18:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/quiet_assets.rb:13:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/request_id.rb:24:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/static.rb:136:in `call'
vendor/bundle/ruby/2.4.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/engine.rb:522:in `call'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/configuration.rb:232:in `call'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/server.rb:578:in `handle_request'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/server.rb:415:in `process_client'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/server.rb:275:in `block in run'
vendor/bundle/ruby/2.4.0/gems/puma-3.7.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
  Rendering vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout
  Rendering vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout
  Rendering vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.2ms)
  Rendering vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered collection of vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/routes/_route.html.erb [2 times] (2.2ms)
  Rendered vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (14.9ms)
  Rendered collection of vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/routes/_route.html.erb [2 times] (2.2ms)
  Rendered vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/routes/_table.html.erb (1.9ms)
  Rendered vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/routes/_table.html.erb (3.4ms)
  Rendering vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (2.1ms)
  Rendered vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (93.8ms)
  Rendering vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.7ms)
  Rendered vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (151.2ms)
^CExiting
```
```console
$ git checkout rails-base 
Switched to branch 'rails-base'
$ rails server
=> Booting Puma
=> Rails 5.0.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.7.1 (ruby 2.4.0-p0), codename: Snowy Sagebrush
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
Started GET "/" for ::1 at 2017-03-03 15:22:17 -0300
Processing by Rails::WelcomeController#index as HTML
  Parameters: {"internal"=>true}
  Rendering vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/templates/rails/welcome/index.html.erb
  Rendered vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/templates/rails/welcome/index.html.erb (4.8ms)
Completed 200 OK in 29ms (Views: 11.4ms)
```

**Comment by alexandre-mbm** [comment]
[Rails App Not Serving Assets in Production Environment](http://stackoverflow.com/questions/17904949/rails-app-not-serving-assets-in-production-environment)
